"""Named constants for the Python SDK."""

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
ANTHROPIC_API_KEY_ENV = "ANTHROPIC_API_KEY"
GEMINI_API_KEY_ENV = "GEMINI_API_KEY"

PROVIDER_DEFAULT_MAX_TOKENS = 4096
PROVIDER_DEFAULT_TEMPERATURE = 0.7
